### ISSUE TITLE
Feat: Implement a structure to represent a car that can be assigned to a player

### ISSUE THREAD

**Issue by KevinMB0220** [SunsetLabs-Game/Citizen-of-Arcanis-BackEnd#11]
**Description**: Implement a structure to represent a car that can be assigned to a player. The car should include basic attributes such as `model` and `speed`. Additionally, create a system that allows assigning the car to a player, ensuring that a car can only be assigned to one player at a time.

- **Requirements**:
  - **Model**: 
    - Create a structure in Cairo to represent the car with the following attributes:
      - `id` (type `felt252`): Unique identifier for the car.
      - `model` (type `felt252`): Name of the car model.
      - `speed` (type `felt252`): Speed of the car.
      - `player_id` (type `Option<felt252>`): Identifier of the player assigned to the car (nullable).

  - **System**: 
    - Develop a `create_car` function to initialize the car with its attributes.
    - Implement an `assign_car_to_player` function to associate a car with a player while ensuring:
      - A car cannot be assigned to multiple players.
      - If a player already owns a car, it cannot be overwritten without unassigning.

  - **Tests**:
    - Validate that a car can be created with the correct attributes.
    - Ensure a car can be assigned to a player and the association is correctly stored.
    - Verify that a car cannot be assigned to more than one player at a time.
    - Confirm that retrieving car details, including the assigned player, functions correctly.

- **Objective**: Provide a foundational system to manage cars and their assignments to players, ensuring data integrity. This implementation will serve as the base for future enhancements, such as advanced customization and assignment rules.

**Comment by RJMadrigal** [comment]
Hello team, can I try to solve this?

**Comment by KevinMB0220** [comment]
> Hi team! can I try to solve this? I am a software engineering student, currently learning about web3 and languages ​​like cairo and rust. To solve this issue, I will create a structure in Cairo that represents a car with the attributes id, model, speed, and player_id. I will implement the create_car function to initialize these attributes and the assign_car_to_player function to assign the car to a player, ensuring that a car cannot be assigned to multiple players at the same time. If a player already has a car, another cannot be assigned without unassigning the previous one. I will run tests to verify car creation, correct assignment, and validation that a car can only have one player assigned to it.

Yes sure

**Comment by KevinMB0220** [comment]
@RJMadrigal Any progress?

**Comment by JoshdfG** [comment]
can i work on this?

**Comment by emarc99** [comment]
Can I handle this task? 
Would love to contribute. I have and deliver within 2 days.

**Comment by derianrddev** [comment]
Hello!
My name is Derian, and I'm part of the ⛩️ Dojo Coding community. I'm a software engineer focused on fullstack web development, with experience in web3 technologies using Starknet and Cairo. I have also been actively contributing to open source projects through OnlyDust, where I solved Cairo problems in projects like GoStarkMe and Stark Cairo Nodes. I would love to contribute and collaborate in the development of this project.

**Comment by KevinMB0220** [comment]
@derianrddev yeah sure
