### ISSUE TITLE
feat: Document the components Files

### ISSUE THREAD

**Issue by KevinMB0220** [SunsetLabs-Game/Citizen-of-Arcanis-BackEnd#18]
# **Issue: Document the `components` Files**

## **Description**
The files in the `components` directory need to be documented to explain the key functions, structures, and variables in the code. The files to document are: `armour.cairo`, `mercenary.cairo`, `stats.cairo`, `utils.cairo`, `weapon.cairo`, and `world.cairo`.

### **Code Documentation**
- Explain the most important functions, structures, and variables.
- Highlight how they relate to each other.

### **Consistency Review**
- Ensure that comments are clear and consistent across all files.

## **Acceptance Criteria**
- Each file contains comments explaining its key parts.
- Comments are clear, relevant, and follow a consistent style.

## **Priority**
Medium

**Comment by ryzen-xp** [comment]
Let me try this one!

**Comment by KevinMB0220** [comment]
@ryzen-xp yeah sure
