### ISSUE TITLE
Feat: Creation of a Basic Pet for the Player

### ISSUE THREAD

**Issue by Josue19-08** [SunsetLabs-Game/Citizen-of-Arcanis-BackEnd#3]
##### Creation of a Basic Pet for the Player
- **Description**: Implement a simple structure to represent a basic pet that will accompany the player. The pet should have simple attributes such as name and type (e.g., dog, cat, dragon) and does not require advanced customization or complex abilities at the start.
- **Requirements**:
  - **Model**: Create a structure in Cairo to represent the pet with at least two attributes: `name` (type `felt`) and `type` (type `felt`).
  - **System**: Develop a `create_pet` function to initialize the pet and assign it to the player at the start of the game.
  - **Tests**: Ensure tests are implemented to validate the creation of pets, correct attribute assignment, and proper association with the player.
- **Objective**: Provide a basic pet that accompanies the player, enhancing gameplay with a quick and simple implementation. This foundation can later be expanded with more complex features and abilities.

**Comment by NueloSE** [comment]
May I try my hand at this?

**Comment by GideonBature** [comment]
Greetings can you please assign this issue to me?

I am a software engineer and have participated and contributed to previous ODHacks. I would love to contribute once again by solving this issue. I have experience working with Cairo. For this project, I will send my first PR within 48 hrs.

Thank you.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity .
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by RJMadrigal** [comment]
Hi team!

I would like to get this opportunity. I am a systems engineer from Costa Rica, with experience in C#, and I am currently learning Cairo and Rust, which makes this project a great opportunity to apply and strengthen my knowledge in Cairo.

It's my first Oddhack and I'm looking for my first contribution, so I'm excited to contribute and learn in this collaborative environment. I commit to implementing the pet model with the necessary attributes, developing the create_pet function to initialize it, and ensuring that full testing is performed to validate its proper functioning and association with the player.

Thank you for considering me!

**Comment by BraCR10** [comment]
Hello maintainers I am BRACR10 a contributor from Dojo Coding, would be a pleasure to attend this issue, I have experience in developing some games using structures and I have the idea of how to implement the logic of this function and its tests.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by jimenezz22** [comment]
Hi! can I help with this issue? I’m actively working with Cairo and Dojo Engine for ByteBeasts, where I’ve gained experience creating models, systems, and tests for on-chain gaming.

For this issue, I’ll:

Model: Define the Pet structure with name and type attributes.
System: Implement the create_pet function to initialize and assign the pet to the player.
Tests: Write comprehensive tests to validate pet creation, attribute assignment, and player association.

This foundational system aligns perfectly with my current experience in Cairo and on-chain gaming logic.

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with experience contributing Cairo project. I would love to work on this.

**Comment by Unickhub** [comment]
Let me handle this issue!

**Comment by Josue19-08** [comment]
Yes sir, it’s yours @jimenezz22

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev, and a blockchain dev kindly assign :)

**Comment by LeonM95** [comment]
Hello,

My name is Leo, and I'm a junior software developer from Costa Rica. This will be my first Hackathon, and I am excited to apply for this issue.

I have experience working with C#, JavaScript, Node.js, and some TypeScript. I will be able to implement this (pet for player) structure and it will help me to immprovde my  coding skills.

Currently, I am also learning about Web3 technologies. Thank you for considering my application.

Best regards,  
Leo

**Comment by jimenezz22** [comment]
> Yes sir, it’s yours @jimenezz22

thanks for the issue, I will start working immediately

**Comment by Josue19-08** [comment]
@jimenezz22 If you update your fork, we will merge
