### ISSUE TITLE
Feat: Creation of a Basic NPC (Non-Player Character) Structure

### ISSUE THREAD

**Issue by Josue19-08** [SunsetLabs-Game/Citizen-of-Arcanis-BackEnd#4]
##### Creation of a Basic NPC (Non-Player Character) Structure
- **Description**: Implement a simple class to represent an NPC (Non-Player Character) within the backend system. NPCs will have basic attributes such as name, type (e.g., merchant, enemy, guide), and a description of their function or characteristics in the game.
- **Requirements**:
  - **Model**: Create a structure in Cairo to represent an NPC, with at least three attributes: `name` (type `felt`), `type` (type `felt`), and `description` (type `felt`).
  - **System**: Develop functions to initialize the NPC and assign values to these attributes, and optionally include a `display_details` function to present NPC information.
  - **Tests**: Create tests to ensure proper initialization, attribute assignment, and output of NPC details (if applicable).
- **Objective**: Provide a foundation for representing NPCs in the system, enabling interactions with players and other game elements.

**Comment by martinvibes** [comment]
I’d like to help with this. 
Kindly assign sir :)

**Comment by Josue19-08** [comment]
Hey Sir :). You must request it from Only Dust and on the dates of ODHack 10

**Comment by GideonBature** [comment]
Greetings can you please assign this issue to me?

I am a software engineer and have participated and contributed to previous ODHacks. I would love to contribute once again by solving this issue. I have experience working with Cairo. For this project, I will send my first PR within 72 hrs.

Thank you.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity .
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by coxmars** [comment]
Hi @KevinMB0220, I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working in ByteBuildersLabs creating on-chain games using the Dojo framework.

This is my approach:

- I will review the project structure to place the models and functions correctly.
- I will create other models or enums as required for this functionality as role and mission_status.
- I will implement all functions required for this.
- Finally, I’ll test the code to ensure all core functionalities work correctly.

ET: I will send a PR tomorrow

**Comment by KevinMB0220** [comment]
> Hi @KevinMB0220, I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working in ByteBuildersLabs creating on-chain games using the Dojo framework.
> 
> This is my approach:
> 
> * I will review the project structure to place the models and functions correctly.
> * I will create other models or enums as required for this functionality as role and mission_status.
> * I will implement all functions required for this.
> * Finally, I’ll test the code to ensure all core functionalities work correctly.
> 
> ET: I will send a PR tomorrow

Yeah sure

**Comment by coxmars** [comment]
> > Hi @KevinMB0220, I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working in ByteBuildersLabs creating on-chain games using the Dojo framework.
> > This is my approach:
> > 
> > * I will review the project structure to place the models and functions correctly.
> > * I will create other models or enums as required for this functionality as role and mission_status.
> > * I will implement all functions required for this.
> > * Finally, I’ll test the code to ensure all core functionalities work correctly.
> > 
> > ET: I will send a PR tomorrow
> 
> Yeah sure

Thanks for the opportunity, I will open the PR tomorrow 🫡
