### ISSUE TITLE
Feat: Management of Rare Items Obtained in Missions or Combats

### ISSUE THREAD

**Issue by KevinMB0220** [SunsetLabs-Game/Citizen-of-Arcanis-BackEnd#7]
##### Management of Rare Items Obtained in Missions or Combats
- **Description**: Implement a system to register and manage rare items obtained by players during missions or by defeating enemies. The system should allow new items to be added to the player's rare item inventory and record their source (specific mission or enemy defeated), while preventing duplicates.
- **Requirements**:
  - **Model**: Create a structure to store rare items acquired by the player, associating each item with a unique identifier or descriptor.
  - **System**: Implement a `register_rare_item` function to add new items and specify the source (mission or enemy). Include logic to prevent duplicates.
  - **Tests**: Write tests to confirm successful item registration, accurate source recording, and prevention of duplicate entries in the inventory.
- **Objective**: Facilitate the management and tracking of acquired rare items, enhancing the player experience through a well-organized rewards system.

**Comment by GideonBature** [comment]
Greetings can you please assign this issue to me?

I am a software engineer and have participated and contributed to previous ODHacks. I would love to contribute once again by solving this issue. I have experience working with Cairo. For this project, I will send my first PR within 48 hrs.

Thank you.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity .
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Let me try this one!

**Comment by JoE11-y** [comment]
I’m interested in this one.

**Comment by KevinMB0220** [comment]
@JoE11-y  How would you solve it?
