### ISSUE TITLE
Feat: Creation of a Class to Represent Factions with Basic Skills

### ISSUE THREAD

**Issue by KevinMB0220** [SunsetLabs-Game/Citizen-of-Arcanis-BackEnd#8]
##### Creation of a Class to Represent Factions with Basic Skills
- **Description**: Implement a class that represents the various factions available in the game, each associated with a basic set of skills. Players should be able to select a faction at the beginning, acquiring its basic skills, with the ability to unlock additional skills as they progress.
- **Requirements**:
  - **Model**: Create a structure representing a faction, including attributes such as `name`, `description`, and an initial list of skills. Create a structure to represent individual skills with attributes like `name` and `effect`.
  - **System**: Develop a `select_faction` function that allows players to choose a faction and acquire its basic skills automatically. Implement logic for unlocking additional skills based on conditions such as player level or achievements.
  - **Tests**: Design tests to validate faction selection, skill acquisition, and unlocking conditions. Verify that players receive the correct set of skills and meet requirements for further unlocking.
- **Objective**: Enable players to select factions with basic skills, fostering initial customization and progression without complex skill systems.

**Comment by mimisavage** [comment]
@KevinMB0220 
I believe I can add value to this task-can I take it on?

**Comment by enyinnaya1234** [comment]
I surely can provide solution to this issue. can i take it on?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by BrayanMQ** [comment]
Can I start working on this? I will solve it in this way: 

Modeling Factions and Skills:

- I will create a Faction class with attributes like name, description, and basic_skills (a list of initial skills).
- A Skill class will represent individual skills with attributes such as name and effect (which could be text or a callable function describing the skill's behavior).
- I’ll establish clear relationships between these classes to ensure scalability.


Selection and Progression System:

- I will implement a select_faction(player, faction) function that: 

   *Allows the player to choose a faction.
   *Automatically assigns the faction's basic skills to the player.

- I will include logic for unlocking additional skills based on predefined conditions, such as the player's level or specific achievements.



Unit Testing:

I will write tests to:
- Ensure that faction selection assigns the correct set of basic skills.
- Validate that players meet the necessary conditions to unlock additional skills.
- Handle edge cases, such as invalid faction selections or players who do not meet the requirements.

**Comment by Unickhub** [comment]
I'd like to take this issue.

**Comment by ShantelPeters** [comment]
Can I take this from here?

**Comment by Josue19-08** [comment]
@BrunoAmbricca Hey Sir, could you provide us with a description of how you would solve it?

**Comment by RJMadrigal** [comment]
Hi team!

I would like to get this opportunity. I am a systems engineer from Costa Rica, with experience in C#, .NET, React and I am currently learning Cairo and Rust, which makes this project a great opportunity to apply and strengthen my knowledge in Cairo.

It's my first ODhack and I'm looking for my first contribution, so I'm excited to contribute and learn in this collaborative environment
