### ISSUE TITLE
Feat: Implementation of a Function to Inflict Damage with Existing Weapons (Sword and Katana)

### ISSUE THREAD

**Issue by KevinMB0220** [SunsetLabs-Game/Citizen-of-Arcanis-BackEnd#9]
##### Implementation of a Function to Inflict Damage with Existing Weapons (Sword and Katana)
- **Description**: Implement a function that uses existing weapon structures (Sword and Katana) to calculate and apply damage to an enemy during combat. The function should accept parameters for the weapon used and the target, calculate the inflicted damage, and update the enemy's health accordingly.
- **Requirements**:
  - **Model**: Ensure existing weapon structures have relevant attributes such as `base_damage`.
  - **System**: Create a function `inflict_damage` that accepts the selected weapon and the enemy's current health, calculates damage, and updates the health.
  - **Tests**: Develop tests to verify correct damage calculation, health reduction, and validation logic (e.g., preventing negative health values).
- **Objective**: Provide a simple yet effective combat function to handle damage application using existing weapons, contributing to core battle mechanics.

**Comment by mimisavage** [comment]
Could I take responsibility for this task?

**Comment by BraCR10** [comment]
Hello maintainers I am BRACR10 a contributor from Dojo Coding, I would like to take this issue as a way to improve my skills in cairo and I have the idea how to implement it, previously I participated in a blockchain development module where I together with a team implemented a similar game idea on Solidity where there were different characters and features that made the percentage of damage vary, despite being another language, it  follows the same logic and can easily adapt to this case! 
Repo:https://github.com/OptimisticCRTeam/on_chain_game

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by codebestia** [comment]
Can i work on this?

**Comment by mimisavage** [comment]
Is it okay if I tackle this?

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing to lots of Cairo code base. Can I work on this?

**Comment by ShantelPeters** [comment]
May I pick this up?

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged:

software engineering background, backend & smart contract dev with contribution to similar tasks(https://app.onlydust.com/u/Josh-121) looking to make first contribution on this project

How I plan on tackling this issue
I understand the requirement to create the required function to use the existing weapon structure ,inflict damage based on weapon damage capcity and update players health accordingly. I have good experience working on gaming tasks like this and can implement this,work on feedback & recommendation ensuring contact. Can deliver within a day upon assignment

**Comment by KevinMB0220** [comment]
Yes sure @BraCR10

**Comment by JoE11-y** [comment]
I'd love to give this a go.
